// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// auc_kernel
List auc_kernel(std::vector < double > test, std::vector < bool > status);
RcppExport SEXP fastAUC_auc_kernel(SEXP testSEXP, SEXP statusSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector < double > >::type test(testSEXP);
    Rcpp::traits::input_parameter< std::vector < bool > >::type status(statusSEXP);
    rcpp_result_gen = Rcpp::wrap(auc_kernel(test, status));
    return rcpp_result_gen;
END_RCPP
}
