# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

auc_kernel <- function(test, status) {
    .Call('fastAUC_auc_kernel', PACKAGE = 'fastAUC', test, status)
}

